[theme]
# app background
backgroundColor = "#CFCAA8"
# for containers/sidebar
secondaryBackgroundColor = "#C35E87"
# Brand accent 
primaryColor = "#0274BD"
# Body text (off-white for contrast)
textColor = "#000000"
# monospace / sans
font = "sans serif"
