[theme]
# app background
backgroundColor = "#FFFFFF"
# for containers/sidebar
secondaryBackgroundColor = "#c6cedbff"
# Brand accent 
primaryColor = "#0274BD"
# Body text (off-white for contrast)
textColor = "#000000"
# monospace / sans
font = "sans serif"
