[theme]
# app background
backgroundColor = "white"
# for containers/sidebar
secondaryBackgroundColor = "#CFCAA8"
# Brand accent 
primaryColor = "#3D155F"
# Body text (off-white for contrast)
textColor = "#000000"
# monospace / sans
font = "sans serif"
