[theme]
# Deep navy app background
backgroundColor = "#FFF4E4"
# Slightly lighter navy for containers/sidebar
secondaryBackgroundColor = "#B1AA81"
# Brand accent (coral/red)
primaryColor = "#0274BD"
# Body text (off-white for contrast)
textColor = "#000000"
# monospace / sans
font = "sans serif"
