# .streamlit/secrets.toml

QUERY_EXPANSION_MODIFIERS = "market size; vendors; tooling; spec; roadmap; 2024; 2025; news; open-source"
LANGSMITH_ENABLED = true
MAX_SOURCES = 10
MIN_NON_EMPTY_SOURCES = 5
CIRCUIT_BREAKER_LIMIT = 3
LLM_MODE = "groq"
GROQ_API_KEY = "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"
GROQ_MODEL = "llama-3.3-70b-versatile"
TAVILY_API_KEY = "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"
SERP_API_KEY = "0a03c8953f0bc7e8dc9afb91e5175c544dcd3a7656dafacc9de5be5745789463"
NEWSAPI_KEY = "f61e0b4c0961409eb6dd2db8a4d095a1"
RAPIDAPI_KEY = "eb60627820msh219fd2bdef68353p153002jsn3f0d386caba6"
URL2MD_HOST = "url-to-markdown-api.p.rapidapi.com"
URL2MD_BASE = "https://url-to-markdown-api.p.rapidapi.com"
URL2MD_ENDPOINT = "/convert"
LANGCHAIN_TRACING_V2 = true
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "market-brief"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
TRACE_DIR = "artifacts"
HTTP_TIMEOUT = 12
